### ISSUE TITLE
Year 2018 arm feedforward

### ISSUE THREAD

**Issue by gaborszita** [frc971/971-Robot-Code#23]
Hey,

I'm Gabor from team 114 and we're looking at your arm feed forward code to try to implement it in our robot. It's in the `y2018/control_loops/python/arm_trajectory.py` file. Can you please explain us a few things?

1. What are the `G1` and `G2` constants? I think this is the gear ratio of the motors, but I'm not 100% sure.

The following questions are not essential to be answered, but if you have time, we'd appreciate if you do

2. What is the difference between the `K2` and `K4` matrices? I understand what the other matrices do, but `K2` and `K4` are both multiplied by omega - which would imply that both are used to relate torque to omega. But I don't understand why you would need two matrices for the same thing. Can you please clarify what the exact purpose of these matrices are?
3. Can you please clarify how exactly the constant matrices are calculated and what the values in it are?

@AustinSchuh @platipus25 I'm pinging you because it seems that you are the contributors to this file, so I assume you know the implementation details.

Thanks in advance,
Gabor and team 114

**Comment by jkuszmaul** [comment]
@gaborszita 

* G1 and G2 are gear ratios for each joint
* K2 and K4 capture different physical effects. K2 has to do with the impacts of centripetal accelerations/coriolis force; K4 has to do with the backEMF of the motors.
* Not sure what you are asking re: constant matrices.

**Comment by AustinSchuh** [comment]
I think we've lost the derivation over time, but the derivation is done using lagrangian mechanics.  These things suck to do by hand.
