### ISSUE TITLE
Better timing report consumption

### ISSUE THREAD

**Issue by jkuszmaul** [frc971/971-Robot-Code#9]
Create one or both of:
* Command line tool to filter timing reports based on application name and display them (with various possibilities for how it is displayed--at a minimum just dumping the straight JSON).
* Plot that breaks out timing report information in a useful manner.

**Comment by bsilver8192** [comment]
I've done this with `jq` before. Would documenting some helpful patterns for that make sense vs writing a tool?

**Comment by AustinSchuh** [comment]
Documentation would be a huge step forwards.  The most annoying part is we log channel numbers, but folks can't remember those.

**Comment by jameskuszmaul-brt** [comment]
I've got a simple version of this downstream that I'll upstream when I have a good chance. Although I do think it'd be cute to take this as an opportunity to experiment with a custom foxglove extension (foxglove extension support for browsers is still a bit irritating to use, however).
